name: Build bad_query IPA

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile as dylib
        run: |
          cd bad_query
          mkdir -p build
          xcrun -sdk iphoneos clang -arch arm64 -shared -o build/bad_query.dylib bad_query.c

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: bad_query_dylib
          path: bad_query/build/bad_query.dylib
